import styles from "../styles/home.module.scss";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.container}>
        <Image
          src={`/logo.jpeg`}
          alt="Picture of the author"
          width={270}
          height={270}
        />

        <p className={styles.title}>
          <strong>Nosso site </strong> será lançado em breve!
        </p>
        <span className={styles.subTitles}>
          Estamos trabalhando para criar a melhor experiência para você.
        </span>

        <span className={styles.description}>
          Enquanto isso, nos siga nas redes sociais.
        </span>
        <div className={styles.imgLink}>
          <Link href="https://github.com/joaotelesk" target="_blank">
            <Image
              src={`/github.svg`}
              alt="imagem github"
              width={30}
              height={30}
            />
          </Link>
          <Link href="https:www.linkedin.com/in/joaotelesk" target="_blank">
            <Image
              src={`/linkedin.svg`}
              alt="imagem linkedin"
              width={30}
              height={30}
            />
          </Link>
        </div>
        <footer className={styles.footer}>&copy; 2023 - joaoteslesk</footer>
      </main>
    </>
  );
}
