// Components
import Head from "next/head";
import Link from "next/link";
import { CardImg } from "../src/components/CardImg/CardImg";
import { Footer } from "../src/components/Footer/Footer";
import { Heading } from "../src/components/Heading/Heading";
import { Logo } from "../src/components/Logo/Logo";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col text-center items-center justify-between h-screen w-full">
        <div className="mt-10">
          <Logo size={36} className="text-white-400 font-bold text-md " />
        </div>

        <main className="w-4/6  mobile:w-5/6">
          <Heading size="sm" className="text-white-400 font-medium ">
            Está página está quase pronta e será lançada logo em breve, fique de
            olho! Enquanto isso, siga nos nas redes sociais pra não perder nada.
          </Heading>
          <div className="desktop:hidden flex gap-2 mt-5 justify-center ">
            <Link href="https://www.linkedin.com/in/joaotelesk">
              <CardImg
                className="shadow-2xl"
                alt="logo linkedin"
                src="/linkedin-purple.svg"
              />
            </Link>
            <Link href="https://github.com/joaotelesk">
              <CardImg alt="logo github" src="/github-purple.svg" />
            </Link>
            <Link href="https://api.whatsapp.com/send?phone=5585988277110">
              <CardImg alt="logo whatsapp" src="/whatsapp-purple.svg" />
            </Link>
            <Link href="https://discord.gg/cDK55jn6">
              <CardImg alt="logo discord" src="/discord-purple.svg" />
            </Link>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}
