import Head from "next/head";
import Link from "next/link";
import { CardImg } from "../src/components/CardImg/CardImg";
import { Footer } from "../src/components/Footer/Footer";

import { Heading } from "../src/components/Heading/Heading";
import { Text } from "../src/components/Text/Text";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col text-center items-center text-center justify-between h-screen w-full">
        <div className="flex mb-4 mt-8 items-center gap-2 ">
          <img src="/logo.svg" alt="minha logo" sizes="34px" />
          <Text className="font-bold text-sm text-white-500">João Teles</Text>
        </div>
        <main className="w-4/6  mobile:w-5/6">
          <Heading
            size="md"
            className="text-white-400 font-medium mobile:text-lg"
          >
            Está página está quase pronta e será lançada logo em breve, fica de
            olho! Enquanto isso, siga nos nas redes sociais pra não perder nada.
          </Heading>
          <div className="desktop:hidden flex gap-2 mt-5 justify-center ">
            <Link href="https://www.linkedin.com/in/joaotelesk">
              <CardImg
                className="shadow-2xl"
                alt="logo linkedin"
                src="/linkedin-purple.svg"
              />
            </Link>
            <Link href="https://github.com/joaotelesk">
              <CardImg alt="logo github" src="/github-purple.svg" />
            </Link>
            <Link href="https://api.whatsapp.com/send?phone=5585988277110">
              <CardImg alt="logo whatsapp" src="/whatsapp-purple.svg" />
            </Link>
            <Link href="https://discord.gg/cDK55jn6">
              <CardImg alt="logo discord" src="/discord-purple.svg" />
            </Link>
          </div>
        </main>
        <Footer className="" />
      </div>
    </>
  );
}
